- name: Ensure cert-manager
  tags:
  - k8s
  - cert-manager
  import_tasks: _cert-manager.yml

- name: Ensure gitea
  tags:
  - k8s
  - gitea
  import_tasks: _gitea.yml

- name: Ensure concourse
  tags:
  - k8s
  - concourse
  import_tasks: _concourse.yml
